<?php
require_once 'db_connect.php';

echo "<h1>🚀 Master Fix: Shop Applications</h1>";

try {
    // 1. DROP and RECREATE the table to ensure it is PERFECT
    $pdo->exec("DROP TABLE IF EXISTS shop_applications");

    $sql = "CREATE TABLE shop_applications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        full_name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        phone VARCHAR(50),
        password_hash VARCHAR(255),
        shop_name VARCHAR(255) NOT NULL,
        business_reg VARCHAR(100),
        address TEXT,
        shop_category VARCHAR(100) NOT NULL,
        years_in_business INT,
        description TEXT,
        status VARCHAR(20) DEFAULT 'pending',
        applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )";
    $pdo->exec($sql);
    echo "<p style='color:green'>✅ Table `shop_applications` re-created successfully.</p>";

    // 2. Insert a TEST APPLICATION
    $testPass = password_hash('test1234', PASSWORD_DEFAULT);
    $insertSql = "INSERT INTO shop_applications 
    (full_name, email, phone, password_hash, shop_name, business_reg, address, shop_category, years_in_business, description, status) 
    VALUES 
    ('Test User', 'testshop@gmail.com', '1234567890', '$testPass', 'Test Pet Shop', 'REG-001', '123 Test St', 'Toys & Accessories', 2, 'This is a test application generated by the system.', 'pending')";

    $pdo->exec($insertSql);
    echo "<p style='color:green'>✅ Test Application inserted intentionally.</p>";

    // 3. Verify it exists
    $stmt = $pdo->query("SELECT count(*) FROM shop_applications");
    $count = $stmt->fetchColumn();

    echo "<h2>📊 Current Applications in DB: " . $count . "</h2>";

    if ($count > 0) {
        echo "<h3 style='color:blue'>🎉 FIX SUCCESSFUL!</h3>";
        echo "<p>Go to <a href='admin-dashboard.php'>Admin Dashboard</a> - you should see 'Test Shop' there now.</p>";
        echo "<p>Then try submitting a real application at <a href='shopowner-apply.php'>Shop Application</a>.</p>";
    } else {
        echo "<h3 style='color:red'>❌ Something is still wrong. Check database permissions.</h3>";
    }

} catch (PDOException $e) {
    echo "<h2 style='color:red'>CRITICAL ERROR: " . $e->getMessage() . "</h2>";
}
?>